### ISSUE TITLE
Allan Variance for accelerometer data

### ISSUE THREAD

**Issue by anfebit** [hanley6/IMUSensorModels#2]
It seems that this code is intended to be used for gyro data "Only". I can see at the code a line where the data is integrated to obtain the angle. 

`% Integration of samples over time to obtain output angle ?
theta = cumsum(meas)/fs; `

Would it be possible to remove this line and run it for accelerometer data too? 

Thank you beforehand.

**Comment by hanley6** [comment]
This line is part of the procedure for computing the Allan variance. This applies equally to gyroscopes and accelerometers. No change is needed for it to work with accelerometer. My comments on the procedure were simply explaining the process for the gyroscope. I will change this comment in a future release and I can provide references on Allan variance if you would like.

**Comment by anfebit** [comment]
That would be great. I will appreciate it a lot. 

I was also wondering, you mentioned on the wiki that the noise can be determined with the following equation. 

 noise = Angle Random Walk + Bias Instability + Rate Random Walk.

In which part of the code can I find such values? I can see that you are finding the values B, N and K. BTW, I don't have toolbox to calculate the PSD.
