### ISSUE TITLE
What is mean by IMU remaining still (i.e gravity vector should be alligned with body z-axis while capturing values) 

### ISSUE THREAD

**Issue by BharadwajaY** [hanley6/IMUSensorModels#4]
Hi,
I have doubt on capturing the raw imu values while IMU remaining still. That means, we have to keep the IMU z-axis aligned with gravity direction. is this interpretation is correct or we can capture the values at any orientation of IMU with gravity direction.

If we can capture at any orientation, the projection of acceleration due to gravity on xy-plane will be coming as a bias in the measurements. is this interpretation is correct?

**Comment by hanley6** [comment]
Hello:

I am confused about what part of the code or my documentation you are referencing. Can you point me in the correct direction? It seems to me that you are asking about quasi-stationary alignment/initialization. But I don't recall including that anywhere in this code or documentation.

Dave

**Comment by BharadwajaY** [comment]
Thank you for your response, 

It is not about the code/documentation part. It is about collecting the raw data of IMU for 4 to 6 hours (After collecting this data we will be giving it as data.mat in the code).

can you suggest me, how IMU should be placed for collecting the raw data? whether IMU z-axis should be aligned with gravity direction?

**Comment by hanley6** [comment]
Oh I see. Thank you for clarifying. For cheap MEMs applications, the orientation of the sensor shouldn't matter. This is because you aren't looking at the average measurement in a sensor, but the noise (read Allan variance) about the average.

For more precise IMU applications, it should be noted that the IMU's Allan variance curves can vary when forces are applied to the sensor (i.e. gravity). I'm unsure how folks at Honeywell and the like deal with this (a rate table would be my guess). But if you just want to do some static testing, then I might put the IMU on a goniometer and create Allan variance curves at several different angles.

I hope that's helpful!
Dave

**Comment by BharadwajaY** [comment]
Sorry for late response, I was studying in brief about Allan variance(I got clarification about noise around mean). I want one more clarification, In your code the input raw data is assumed as  noise free for stochastic model, so could you help me in finding the scale factor and axis misalignment etc errors of IMU before collecting the data.

**Comment by hanley6** [comment]
There are a few different testing procedures that people use to find these parameters. One reference I recommend is:

D. Titterton and J. Weston. "_Strapdown Inertial Navigation Technology_." The Institution of Engineering and Technology. 2nd Edition. 2004.

In particular, Chapters 8 and 10 cover most of the testing procedure and estimation process for scale factor and axis misalignment. Another reference is:

Paul G. Savage. "_Strapdown Analytics_." Vol. 1 and 2. Second Edition. Strapdown Associates. 2007.

Savage's book covers the estimation process in detail, but does not go into the testing procedure very much. 

I'm sure that there are some other references available on the web (through IEEE Xplore, Spinger Link, etc.) that also discuss this topic in much greater clarity and detail than I could possibly do.

Hope that helps!
Dave

**Comment by BharadwajaY** [comment]
Thank you once again for valuable info and references. my doubt regarding collecting data is cleared. 

Bharadwaja Yathirajam
