### ISSUE TITLE
pwelch error

### ISSUE THREAD

**Issue by ravindraji4** [hanley6/IMUSensorModels#5]
Dear David, 
Thank you very much for sharing the code and knowledge. 

I encountered an error for **Power Spectral Density** on 2018b matlab. 

![image](https://user-images.githubusercontent.com/26116885/83432160-c21c9b80-a438-11ea-9d62-632e4a235c8f.png)

tried searching google, but unable to solve. 
Could you please help. 
Thank you very much in advance. 
Regards,

**Comment by hanley6** [comment]
Hi,

I'm not sure that I have enough information to address this issue, because I don't know what data you have providing the pwelch command. Could you let me know what that data looks like (e.g, its shape)?

Thanks,
Dave

**Comment by ravindraji4** [comment]
Hello Dave, 
Thank you very much for your reply. At first I used the dataset you provided; I have no idea why I am having error only with pwelch; whereas the Allan variance works perfectly fine!

Then, I collected my own dataset using the Xsens IMU and it worked. See the following plot 

![PSD](https://user-images.githubusercontent.com/26116885/84245578-8bfcad00-ab05-11ea-87a7-ee995465ab93.JPG)

Do you how we can estimate the Slop of PSD curve for Accelerometer and Gyroscope X-Y-Z axes?

Regards, 
Ravi

**Comment by hanley6** [comment]
Ravi:

That seems odd. I just ran it again on my computer using MATLAB R2016a and I had no problems. However, I am glad that the code runs your data just fine. I do not compute the slope of the PSD curve anywhere in my code. I'm not sure how people usually go about doing that, but I'm sure that there is a method out there.

Best,
Dave
